### ISSUE TITLE
Bloom Open Graph Metadata preview is not working

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#946] opened 2024-06-04 20:19 UTC
**Describe the bug**
When I share bloom on facebook I see this:
<img width="238" alt="Screenshot 2024-06-04 at 19 21 03" src="https://github.com/chaynHQ/bloom-frontend/assets/16049515/4621c22a-122d-4516-8514-e63f5916e4dc">

**To Reproduce**

1. Go to facebook messager
2. Send a message with Bloom.chayn.co in the content. 
3. Look at the image that is shared. 

**Expected behavior**
We should see the image. 

The image should be this one:

![bloom_socials_preview](https://github.com/chaynHQ/bloom-frontend/assets/16049515/564be9be-9890-407c-9f37-b54b45856549)

**Desktop (please complete the following information):**
- IOS
- Chrome
- Version  125

**Resources:**

- [how to test open graph meta data locally](https://stackoverflow.com/questions/8569892/how-to-test-open-graph-on-localhost)

**Comment by anmol-fzr** [comment] 2024-06-05 03:01
@eleanorreem I would like to work on this issue. Please assign me this one

**Comment by kyleecodes** [comment] 2024-06-14 20:14
@anmol-fzr thank you for your patience. Are you still interested in being assigned this issue? Let us know and we will assign you ASAP as its a high priority issue.

**Comment by anmol-fzr** [comment] 2024-06-15 01:06
@kyleecodes. Yes, I am interested in contribution.

**Comment by anmol-fzr** [comment] 2024-06-16 03:31
@kyleecodes Issue isn't assigned to me yet, but as the issue is high priority. I'm raising a PR fixing this

**Closed** 2024-07-08 09:39 UTC
Labels: bug fix, complexity: moderate, state: approved, priority: high
